services:
  web:
    build:
      context: ./web
    volumes:
      - ./web:/app
      - /app/node_modules

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
  
  nginx:
    image: nginx:latest 
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 