services:
  web:
    build:
      context: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"